[package]
name = "embedded-text"
version = "0.3.0"
license = "MIT"
description = "TextBox for embedded-graphics"
repository = "https://github.com/bugadani/embedded-text"
authors = ["Dániel Buga <bugadani@gmail.com>"]
keywords = ["embedded-graphics", "textbox", "text"]
categories = ["no-std", "embedded", "graphics"]
edition = "2018"

exclude = [
    ".gitignore",
    ".github/",
]

[[bench]]
name = "render"
harness = false

[[bench]]
name = "parse"
harness = false

[dependencies]
embedded-graphics = "0.7.0-alpha.1"
ansi-parser = "0.7.0"
as-slice = "0.1.4"

[dev-dependencies]
embedded-graphics-simulator = "0.2.1"
# embedded-graphics-simulator = {git = "https://github.com/jamwaffles/embedded-graphics/tree/master/simulator"}
sdl2 = "0.32.2"
criterion = "0.3.3"
heapless = "0.5.6"
